server:
  port: 8073

spring:
  application:
    name: college-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        register-enabled: true
        namespace: public
      config:
        import-check:
          enabled: false
    compatibility-verifier:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/academic_warning_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&tinyInt1isBit=false
    username: root
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  type-aliases-package: com.academic.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    root: INFO
    com.academic: DEBUG
